language: c
compiler:
  - gcc
env:
  secure: "mBM7b8Qji+nchfR9VpxXf1CsnkCdH2RZ4Bf+WYzbLqQtyiIWU7YfbK3BqbSGHac7Vd6ztB8EuyiJHv7po2wqYka7QIsmmOTiTJk9y4N7Gqb+0P53Ni6yo2CmkUyC9ziRBaO3fWQ85mQx236sCYQluAD0z0QtOc74ywjxD6ONNy8="
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq curl wget libgc1c2"
  - "mkdir liberty"
  - "curl -s http://apt.liberty-eiffel.org/dists/snapshot/main/binary-amd64/Packages.gz | zcat | awk '/^Package:/ {pkg=$2} /^Version:/ {ver=$2} /^Architecture:/ {arch=$2} /^$/ {printf(\"http://apt.liberty-eiffel.org/pool/main/libe/liberty-eiffel/%s_%s_%s.deb\\n\", pkg, ver, arch)}' | while read pkg; do wget -nd -nH -P liberty -m $pkg; done"
  - "sudo dpkg -i liberty/*.deb"
install:
  - "./deploy.sh"
script:
  - "test -d test && se test -verbose test"
after_failure:
  - "cat test/eiffeltest/log.ref"
after_success:
  - "rsync -aSHv --stats -e ssh target/*.tgz $RSYNC:~/pwd/target/"
cache:
  apt: true
  directories:
    - liberty
